{"text": "2024-08-30 02:38:01 | INFO    | __main__:stash:131 | run - {'image': '20231121', 'version': '0.10.1.post2', 'role': 'EpicPlayer', 'headless': True}\n", "record": {"elapsed": {"repr": "0:00:01.045480", "seconds": 1.04548}, "exception": null, "extra": {"image": "20231121", "version": "0.10.1.post2", "role": "EpicPlayer", "headless": true}, "file": {"name": "claim.py", "path": "/home/runner/work/epicnew/epicnew/epic/src/claim.py"}, "function": "stash", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 131, "message": "run", "module": "claim", "name": "__main__", "process": {"id": 3663, "name": "MainProcess"}, "thread": {"id": 139949697252224, "name": "MainThread"}, "time": {"repr": "2024-08-30 02:38:01.875374+08:00", "timestamp": 1724956681.875374}}}
{"text": "2024-08-30 02:38:05 | WARNING    | epic_games.agent:get_order_history:467 | Failed to get order history, cookie may have expired - {}\n", "record": {"elapsed": {"repr": "0:00:04.667087", "seconds": 4.667087}, "exception": null, "extra": {}, "file": {"name": "agent.py", "path": "/home/runner/work/epicnew/epicnew/epic/src/epic_games/agent.py"}, "function": "get_order_history", "level": {"icon": "‚ö†Ô∏è", "name": "WARNING", "no": 30}, "line": 467, "message": "Failed to get order history, cookie may have expired", "module": "agent", "name": "epic_games.agent", "process": {"id": 3663, "name": "MainProcess"}, "thread": {"id": 139949697252224, "name": "MainThread"}, "time": {"repr": "2024-08-30 02:38:05.496981+08:00", "timestamp": 1724956685.496981}}}
{"text": "2024-08-30 02:38:06 | DEBUG    | __main__:create_tasks:66 | Put task - {'title': 'Wild Card Football', 'url': 'https://store.epicgames.com/en-US/p/wild-card-football'}\n", "record": {"elapsed": {"repr": "0:00:05.212083", "seconds": 5.212083}, "exception": null, "extra": {"title": "Wild Card Football", "url": "https://store.epicgames.com/en-US/p/wild-card-football"}, "file": {"name": "claim.py", "path": "/home/runner/work/epicnew/epicnew/epic/src/claim.py"}, "function": "create_tasks", "level": {"icon": "üêû", "name": "DEBUG", "no": 10}, "line": 66, "message": "Put task", "module": "claim", "name": "__main__", "process": {"id": 3663, "name": "MainProcess"}, "thread": {"id": 139949697252224, "name": "MainThread"}, "time": {"repr": "2024-08-30 02:38:06.041977+08:00", "timestamp": 1724956686.041977}}}
{"text": "2024-08-30 02:38:06 | DEBUG    | __main__:create_tasks:66 | Put task - {'title': 'Fallout¬Æ Classic Collection', 'url': 'https://store.epicgames.com/en-US/bundles/fallout-classic-collection'}\n", "record": {"elapsed": {"repr": "0:00:05.212539", "seconds": 5.212539}, "exception": null, "extra": {"title": "Fallout¬Æ Classic Collection", "url": "https://store.epicgames.com/en-US/bundles/fallout-classic-collection"}, "file": {"name": "claim.py", "path": "/home/runner/work/epicnew/epicnew/epic/src/claim.py"}, "function": "create_tasks", "level": {"icon": "üêû", "name": "DEBUG", "no": 10}, "line": 66, "message": "Put task", "module": "claim", "name": "__main__", "process": {"id": 3663, "name": "MainProcess"}, "thread": {"id": 139949697252224, "name": "MainThread"}, "time": {"repr": "2024-08-30 02:38:06.042433+08:00", "timestamp": 1724956686.042433}}}
{"text": "2024-08-30 02:38:12 | INFO    | epic_games.agent:claim_weekly_games:294 | claim_weekly_games - {'action': 'go to store', 'url': 'https://store.epicgames.com/en-US/p/wild-card-football'}\n", "record": {"elapsed": {"repr": "0:00:11.788127", "seconds": 11.788127}, "exception": null, "extra": {"action": "go to store", "url": "https://store.epicgames.com/en-US/p/wild-card-football"}, "file": {"name": "agent.py", "path": "/home/runner/work/epicnew/epicnew/epic/src/epic_games/agent.py"}, "function": "claim_weekly_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 294, "message": "claim_weekly_games", "module": "agent", "name": "epic_games.agent", "process": {"id": 3663, "name": "MainProcess"}, "thread": {"id": 139949697252224, "name": "MainThread"}, "time": {"repr": "2024-08-30 02:38:12.618021+08:00", "timestamp": 1724956692.618021}}}
{"text": "2024-08-30 02:38:25 | SUCCESS    | epic_games.agent:claim_weekly_games:314 | Pass claim task - {'reason': 'Free games not added to shopping cart'}\n", "record": {"elapsed": {"repr": "0:00:24.977329", "seconds": 24.977329}, "exception": null, "extra": {"reason": "Free games not added to shopping cart"}, "file": {"name": "agent.py", "path": "/home/runner/work/epicnew/epicnew/epic/src/epic_games/agent.py"}, "function": "claim_weekly_games", "level": {"icon": "‚úÖ", "name": "SUCCESS", "no": 25}, "line": 314, "message": "Pass claim task", "module": "agent", "name": "epic_games.agent", "process": {"id": 3663, "name": "MainProcess"}, "thread": {"id": 139949697252224, "name": "MainThread"}, "time": {"repr": "2024-08-30 02:38:25.807223+08:00", "timestamp": 1724956705.807223}}}
{"text": "2024-08-30 02:38:25 | INFO    | epic_games.agent:claim_bundle_games:351 | claim_bundle_games - {'action': 'go to store', 'url': 'https://store.epicgames.com/en-US/bundles/fallout-classic-collection'}\n", "record": {"elapsed": {"repr": "0:00:24.977942", "seconds": 24.977942}, "exception": null, "extra": {"action": "go to store", "url": "https://store.epicgames.com/en-US/bundles/fallout-classic-collection"}, "file": {"name": "agent.py", "path": "/home/runner/work/epicnew/epicnew/epic/src/epic_games/agent.py"}, "function": "claim_bundle_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 351, "message": "claim_bundle_games", "module": "agent", "name": "epic_games.agent", "process": {"id": 3663, "name": "MainProcess"}, "thread": {"id": 139949697252224, "name": "MainThread"}, "time": {"repr": "2024-08-30 02:38:25.807836+08:00", "timestamp": 1724956705.807836}}}
{"text": "2024-08-30 02:38:56 | INFO    | epic_games.agent:claim_bundle_games:351 | claim_bundle_games - {'action': 'go to store', 'url': 'https://store.epicgames.com/en-US/bundles/fallout-classic-collection'}\n", "record": {"elapsed": {"repr": "0:00:55.480573", "seconds": 55.480573}, "exception": null, "extra": {"action": "go to store", "url": "https://store.epicgames.com/en-US/bundles/fallout-classic-collection"}, "file": {"name": "agent.py", "path": "/home/runner/work/epicnew/epicnew/epic/src/epic_games/agent.py"}, "function": "claim_bundle_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 351, "message": "claim_bundle_games", "module": "agent", "name": "epic_games.agent", "process": {"id": 3663, "name": "MainProcess"}, "thread": {"id": 139949697252224, "name": "MainThread"}, "time": {"repr": "2024-08-30 02:38:56.310467+08:00", "timestamp": 1724956736.310467}}}
{"text": "2024-08-30 02:39:26 | INFO    | epic_games.agent:claim_bundle_games:351 | claim_bundle_games - {'action': 'go to store', 'url': 'https://store.epicgames.com/en-US/bundles/fallout-classic-collection'}\n", "record": {"elapsed": {"repr": "0:01:25.983013", "seconds": 85.983013}, "exception": null, "extra": {"action": "go to store", "url": "https://store.epicgames.com/en-US/bundles/fallout-classic-collection"}, "file": {"name": "agent.py", "path": "/home/runner/work/epicnew/epicnew/epic/src/epic_games/agent.py"}, "function": "claim_bundle_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 351, "message": "claim_bundle_games", "module": "agent", "name": "epic_games.agent", "process": {"id": 3663, "name": "MainProcess"}, "thread": {"id": 139949697252224, "name": "MainThread"}, "time": {"repr": "2024-08-30 02:39:26.812907+08:00", "timestamp": 1724956766.812907}}}
{"text": "2024-08-30 02:39:56 | ERROR    | __main__:run:158 | An error has been caught in function 'run', process 'MainProcess' (3663), thread 'MainThread' (139949697252224): - {}\nTraceback (most recent call last):\n  File \"/home/runner/work/epicnew/epicnew/epic/src/claim.py\", line 162, in <module>\n    asyncio.run(run())\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 636, in run_until_complete\n    self.run_forever()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n    self._run_once()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n    handle._run()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n> File \"/home/runner/work/epicnew/epicnew/epic/src/claim.py\", line 158, in run\n    await agent.stash()\n  File \"/home/runner/work/epicnew/epicnew/epic/src/claim.py\", line 151, in stash\n    await self.claim_epic_games(context)\n  File \"/home/runner/work/epicnew/epicnew/epic/src/claim.py\", line 124, in claim_epic_games\n    await epic.claim_bundle_games(page, bundle_promotions)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 189, in async_wrapped\n    return await copy(fn, *args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 111, in __call__\n    do = await self.iter(retry_state=retry_state)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 153, in iter\n    result = await action(retry_state)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/tenacity/_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/tenacity/__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/tenacity/__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/concurrent/futures/_base.py\", line 451, in result\n    return self.__get_result()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/concurrent/futures/_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 114, in __call__\n    result = await fn(*args, **kwargs)\n  File \"/home/runner/work/epicnew/epicnew/epic/src/epic_games/agent.py\", line 352, in claim_bundle_games\n    await page.goto(promotion.url, wait_until=\"load\")\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/async_api/_generated.py\", line 8805, in goto\n    await self._impl_obj.goto(\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_page.py\", line 524, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://store.epicgames.com/en-US/bundles/fallout-classic-collection\", waiting until \"load\"\n\n", "record": {"elapsed": {"repr": "0:01:56.129917", "seconds": 116.129917}, "exception": {"type": "TimeoutError", "value": "Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://store.epicgames.com/en-US/bundles/fallout-classic-collection\", waiting until \"load\"\n", "traceback": true}, "extra": {}, "file": {"name": "claim.py", "path": "/home/runner/work/epicnew/epicnew/epic/src/claim.py"}, "function": "run", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 158, "message": "An error has been caught in function 'run', process 'MainProcess' (3663), thread 'MainThread' (139949697252224):", "module": "claim", "name": "__main__", "process": {"id": 3663, "name": "MainProcess"}, "thread": {"id": 139949697252224, "name": "MainThread"}, "time": {"repr": "2024-08-30 02:39:56.959811+08:00", "timestamp": 1724956796.959811}}}
